// <auto-generated />
using System;
using BlazorProducts.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorProducts.Api.Data.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorProducts.Api.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("488aaa0e-aa7e-4820-b4e9-5715f0e5186e"),
                            Description = "Genius comes in many forms - whether you're dangerously funny, creating havoc with wild plants, or flooding the island with your best intentions; it often comes along with a companion: madness. Includes:",
                            ImageUrl = "https://store-images.s-microsoft.com/image/apps.19885.14562853408080210.9df454fb-cd8a-4578-8b7c-71ceeede0d82.31554d73-4891-42e0-bc00-3d38999fe6f5?mode=scale&q=90&h=300&w=200&background=%23FFFFFF",
                            Name = "Fortnite - The Last Laugh Bundle",
                            Price = 25.0,
                            Supplier = "‪Epic Games Inc.‬"
                        },
                        new
                        {
                            Id = new Guid("4e693871-788d-4db4-89e5-dd7678db975e"),
                            Description = "Gears 5 is completely refreshed. Get the celebrated campaign, recharged multiplayer and Hivebusters campaign expansion as part of the Game of the Year Edition.",
                            ImageUrl = "https://store-images.s-microsoft.com/image/apps.27223.14591801423393397.b86e1d42-e161-4ada-971f-c3354763da8a.918305fb-c146-4d2e-895a-b40f8fd23ab1?mode=scale&q=90&h=300&w=200&background=%23FFFFFF",
                            Name = "Xbox Game Studios",
                            Price = 35.0,
                            Supplier = "Code Maze"
                        },
                        new
                        {
                            Id = new Guid("2d3c2abe-85ec-4d1e-9fef-9b4bfea5f459"),
                            Description = "The Ultimate Fighter Bundle delivers the ultimate 1-2 punch, combining both of NetherRealm Studios' blockbuster fighting franchises in one knockout package. Includes Mortal Kombat 11 Ultimate and Injustice™ 2 - Legendary Edition.",
                            ImageUrl = "https://store-images.s-microsoft.com/image/apps.60833.13792213938743512.bd91b2c1-db40-4d72-8440-88232c27c7cc.d18d1d59-711c-445d-ad84-8cee0d346d2c?mode=scale&q=90&h=300&w=200&background=%23FFFFFF",
                            Name = "Mortal Kombat 11 Ultimate + Injustice 2 Leg.Edition Bundle",
                            Price = 45.0,
                            Supplier = "Warner Bros. Interactive Entertainment"
                        },
                        new
                        {
                            Id = new Guid("d1f22836-6342-480a-be2f-035eeb010fd0"),
                            Description = "Play as Thanks A Million Johnny Cage, a thank you from Johnny Cage to his millions of fans!",
                            ImageUrl = "https://store-images.s-microsoft.com/image/apps.64948.13866527031028707.c50ab550-0e1e-45dc-bbc3-0df22c0a9826.daa71816-6d49-4684-a45f-8690f6ef9878?mode=scale&q=90&h=300&w=200&format=jpg",
                            Name = "Thanks A Million Johnny Cage",
                            Price = 25.0,
                            Supplier = "Warner Bros. Interactive Entertainment"
                        },
                        new
                        {
                            Id = new Guid("afa40031-c5ff-41ec-acbd-e22d1acebc85"),
                            Description = "Emperor of Outworld. For millennia, Shao Kahn dominated the realms, rapidly expanding his Empire by conquest. But when he set out to claim",
                            ImageUrl = "https://store-images.s-microsoft.com/image/apps.8648.69729254396770513.18e780c7-4c96-46dc-b15b-2fada18780b0.19973a6f-4cce-4451-b377-b8028976cb46?mode=scale&q=90&h=300&w=200&format=jpg",
                            Name = "Shao Kahn",
                            Price = 25.0,
                            Supplier = "Warner Bros. Interactive Entertainment"
                        },
                        new
                        {
                            Id = new Guid("80e33b75-5192-4c57-8553-c3f6c79a29c6"),
                            Description = "Unleash your imagination and create a unique world of Sims that’s an expression of you! Explore and customize every detail from Sims to homes, and much more. Choose how Sims look, act, and dress, then build and design their incredible homes.",
                            ImageUrl = "https://store-images.s-microsoft.com/image/apps.53697.64737940845214615.82a9a5cd-32c5-4fb1-a951-2a7b976ad460.f0e0779f-450f-421f-b0c6-7b04bf25fa60?mode=scale&q=90&h=300&w=200",
                            Name = "The Sims™ 4",
                            Price = 50.0,
                            Supplier = "Electronic Arts‬"
                        },
                        new
                        {
                            Id = new Guid("95ad2ba0-4864-4d47-be4d-22f41324ce07"),
                            Description = "Gang Beasts is a silly multiplayer party game with surly gelatinous characters, brutal slapstick fight sequences, and absurd hazardous environments, set in the mean streets of Beef City.",
                            ImageUrl = "https://store-images.s-microsoft.com/image/apps.35593.68150164172276526.ddc374d7-ef5e-43b9-940a-bbc04440bb33.e0c05607-881c-449f-826b-fec43403598c?mode=scale&q=90&h=300&w=200",
                            Name = "Gang Beasts",
                            Price = 15.0,
                            Supplier = "Boneloaf‬"
                        },
                        new
                        {
                            Id = new Guid("aeb48c8e-a426-4e9c-81f3-a35206a66d49"),
                            Description = "Get 3 times the mayhem, 3 times the loot, and 3 times the action with the Borderlands Legendary Collection!",
                            ImageUrl = "https://store-images.s-microsoft.com/image/apps.29359.13544035497810545.ca0e1ab6-caad-4791-8f56-a4ce8896d945.cd29937c-6c31-4e67-960a-b68319c258a5?mode=scale&q=90&h=300&w=200&background=%23FFFFFF",
                            Name = "Borderlands Legendary Collection",
                            Price = 56.0,
                            Supplier = "2K"
                        },
                        new
                        {
                            Id = new Guid("4bbb7906-ad1b-4e79-abfb-2fda7828568e"),
                            Description = "The critically acclaimed and award winning masterpiece arrives with Bonus Content including Director’s Walkthrough commentary, Art and Sound Gallery. Guide two brothers at the same time in co-op play in single player, on an unforgettable journey from visionary Swedish film director Josef Fares",
                            ImageUrl = "https://store-images.s-microsoft.com/image/apps.54833.67312949670211111.e02ca682-7627-49bb-a230-6f831f2e93d2.ba364000-a28e-4117-b936-c0d1b77af8a5?mode=scale&q=90&h=300&w=200",
                            Name = "Brothers: a Tale of Two Sons",
                            Price = 29.0,
                            Supplier = "505 Games‬"
                        },
                        new
                        {
                            Id = new Guid("c7d56007-0bf8-4fcf-bf05-34d704e284ed"),
                            Description = "Enjoy two amazingly fun and critically acclaimed first person shooters with the DOOM and Wolfenstein II bundle!",
                            ImageUrl = "https://store-images.s-microsoft.com/image/apps.38228.67745962660347843.de2eb3d7-c916-4aba-a659-00fc668328b3.c1fd0971-803b-48c2-9acb-18df5c9ed7bc?mode=scale&q=90&h=300&w=200&background=%23FFFFFF",
                            Name = "DOOM + Wolfenstein II Bundle",
                            Price = 45.0,
                            Supplier = "Bethesda Softworks"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
